import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [cambios,setCambios] =useState(null)
  const changefile = e => {
    const reader = new FileReader()

    reader.readAsDataURL(e.target.files[0])

    reader.onload = e =>{
      e.preventDefault()

      setCambios(e.target.result)
    }
   
  }
  return (
    <div>
      <Head>
        <title>arrastrar y soltar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.filecontent}>
        <input 
          className={styles.input} 
          type="file" 
          accept='' 
          onChange={e => changefile(e)}>
          </input>
      </div>
      <div>
        <img src={cambios}></img>
      </div>
    </div>
  )
}
